# Generated by Django 6.0.4 on 2026-05-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='news_pics/', verbose_name='Hoặc tải ảnh lên từ máy'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Hoặc dán link ảnh'),
        ),
    ]
