# Generated by Django 6.0.4 on 2026-05-24 06:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_options_post_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tin tiêu điểm (Admin tích)'),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hoặc tải ảnh lên từ máy'),
        ),
    ]
