# Generated by Django 6.0.4 on 2026-06-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_post_categories_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
            ],
            options={
                'verbose_name': 'Người đăng ký',
                'verbose_name_plural': 'Người đăng ký newsletter',
            },
        ),
    ]
