# Generated by Django 6.0.4 on 2026-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=20, verbose_name='Đội A')),
                ('team_b', models.CharField(max_length=20, verbose_name='Đội B')),
                ('score_a', models.IntegerField(default=0, verbose_name='Tỷ số A')),
                ('score_b', models.IntegerField(default=0, verbose_name='Tỷ số B')),
                ('status', models.CharField(choices=[('live', 'Live'), ('ht', 'Hiệp 1'), ('ft', 'FT')], default='live', max_length=10, verbose_name='Trạng thái')),
                ('match_date', models.DateField(auto_now_add=True, verbose_name='Ngày đấu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
            ],
            options={
                'verbose_name': 'Tỷ số trực tiếp',
                'verbose_name_plural': 'Tỷ số trực tiếp',
                'ordering': ['-updated_at'],
            },
        ),
    ]
